### ISSUE TITLE
2018年、受付が混乱した理由をまとめる

### ISSUE THREAD

**Issue by fumikito** [wct2019/app-project#4]
- [x] どのぐらい混雑したか
- [x] 混雑の原因に関するヒアリング
- [x] 具体的な受付の作業内容
- [x] 理想的なワークフローの調整

**Comment by lunaluna** [comment]
ちょっと思いつくままですが。

## どのぐらい混雑したか
- エレベーターホールまで受付の列が並ぶくらい。列を整理する・来場者に声掛けする担当者もおらず（いたけれど少なかった？）、一時騒然となっていた。

## 混雑の原因に関するヒアリング
- 受付方法が受付担当者（当日ボランティア）に周知されていなかった？
- そもそも受付の数が適正だったか

## 具体的な受付の作業内容（昨年の場合）
- 来場者にCamptixの返信メールにある登録画面を表示してもらう
    - この時点で表示できない来場者も結構いた模様
- CamptixからDLしたCSVデータをGoogleスプレッドシートで共有しており、その中から該当者を検索
    - 受付担当者が各自自分のPCを受付で開いて確認
        - 検索方法が周知されていなかった？
    - 開場後もチケット販売が継続していたため、その場でチケットを購入した来場者がスプレッドシートに反映されていなかった
    - スピーカー・スポンサー専用の受付がわかりにくかった？（受付テーブルには区分が貼ってあったはずだが、受付中の来場者によって隠れてしまい区別が見えなかった可能性）
- 確認後、ペアになった受付担当者がパンフレット、ネックバンドなど一式を渡す
    - 撮影の可不可など、申し込み形態の違いによる受付場所が分かれておらず、流れ作業での受付がスムーズでなかった
    - 2人がペアで1人の来場者の対応をしていたため、スタッフ側の受付が非常に狭く、実質の受付窓口がそれほど多くなかった？

## 理想的なワークフローの調整
- 前日にリマインドのメールが送信できるなら送信したほうがよい
    - もしかしたら送っていたのかも
- メールを表示してもらう際、送信元から検索するのがいいのか、タイトルをわかりやすいものにするか
- 単純に開場からセッション開始までの時間に余裕を作る（昨年は30分？）
- 今回ロビーで受付をするとして、受付後の来場者の流れを交差しないようにする動線が必要
    - 通路を横切って受付の列が伸びる可能性
    - 朝イチの受付のピークが過ぎた後、ロビー奥が受付だと受付せずに会場内への出入りができてしまうかも？

**Comment by torounit** [comment]
## どのぐらい混雑したか / 混雑の原因に関するヒアリング / 具体的な受付の作業内容

同上。

## 理想的なワークフローの調整

受付のレイアウトも適切で無かったと思われる。

「ホテルのカウンター形式」での受付だったので、受け付け終了後の出口の導線も整備されておらず、受付周辺に人が溜まり、更に混乱したのではないかと。

コンサートなどでよくあるような、出入り口付近に縦に机を並べて出入り口をしっかり分ける、会場前などに列整理(受付の机の数に合わせて) などをすればよいのかなと。エレベーター前に人が溜まってしまうのであれば、会場の出入り口のなかで列整理。( チケットの種類で列を分けるかは数に応じて )

パンフレットなど全ての来場者に渡すモノは、受付では無く受付を通過した時点で配布。

**Comment by tsubasagit** [comment]
**混雑の原因に関するヒアリング**
-受付窓口が一列しかなかった。
-スポンサー、一般受付ともに同じ列から並んでいたので、入口で選別に時間がかかった。
-受付スタッフのパソコンの充電が切れてたが充電する場所が無く、窓口担当が減


**具体的な受付の作業内容**
-入口の列に対して、一般or スポンサーに振り分ける
-担当者名から、Googleスプレッドシートを検索
-パンフレットを渡す

**理想的なワークフローの調整**
##列の並び方
一般とスポンサーをそれぞれ別の列に並ばせたい
最初の会議室Aルーム方面なのか？Hルーム方面なのか？によって受付窓口および列を２つにしたい

##受付方法
-名前の検索ではなく、No.で検索したい。
 　（例）登録No 0111 ミヤザキツバサ　など
-参加状表示用のQRコードを会場前に配る or リマインドメールする or 当日スタッフに渡しておく などで簡易に開けるようにする
![2019-07-04_18h28_04](https://user-images.githubusercontent.com/17616709/60677904-c6090c00-9ebd-11e9-9803-396ccacae1c8.png)

**Comment by fumikito** [comment]
こうしてみると、オペレーションの問題が結構あるような気もしますね。
導線設計をしっかりした上で、その導線を助けるようなアプリを作るといいのかも。
台湾のチームは

- QRコードを読み取る
- メアドかなにかを入力
- そうすると、携帯の画面に必要なもの（スワッグのサイズ、名前など）が表示される
- スタッフはそれを見て必要なものを渡す

といった流れだったようです。
よく考えたら、ユーザーの同定をアプリでやるというより、「スタッフへの指示を伝えるためのものを作る」と考えた方がいいのかも。

引き続き、アイデア募集中です。あと、作成の過程で導線をきちんと決めることもワークフローに入れた方がよさそうですね。

**Comment by torounit** [comment]
例えば、会場の受付前が混雑してるから、一階で待機列を作らせて、そこら変の情報をやりとりするしくみとかは、あっても良いかなと。もしかしたら、トランシーバーとかでやれることなのかも？

**Comment by fumikito** [comment]
理由についてはわかりました。ありがとうございます。
いったんまとめると、こんな感じでしょうか。

## 混雑の経緯

1. 受付の処理速度が遅かった
2. 結果、ロードアベレージが高まった
3. エレベーターホールまで人が溢れた

## 混雑回避の方法

1. 人をすぐに特定できるようにする
2. 人の特定ののち、受け取るものを分ける
3. 人の分類と特典の受け取りを二箇所に分ける
4. 人の導線の整理をあらかじめ決めておく

したがって、アプリとしてできそうな要件は

1. 人をすぐに特定できる
2. その人が受け取れるものがすぐにわかる

の2点かなぁと思いました。
